name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # устанавливаем Docker для кросс-платформенной сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Собираем образы - контейнеры
      - name: Build Docker Compose services
        run: |
          docker-compose build

      # -d - запуск готовых контейнеров в фоновом режиме
      - name: Run test
        run: |
          docker-compose up -d
          
    deploy:
       runs-on: ubuntu-latest
       needs: build
       
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Deploy
           run: |
              echo "Deploying to production..."
