version: '3'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./java
      dockerfile: Dockerfile
    image: javaapp:latest
    ports:
      - "8080:8080"
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/company?useSSL=false&serverTimezone=UTC

volumes:
  db_data:
