version: '3'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./java
      dockerfile: Dockerfile
    image: javaapp:latest
    ports:
      - "8080:8080"
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps
    depends_on:
      - db

volumes:
  db_data:

jobs:
  build:
    - name: Stop services
      if: always()
      run: docker-compose down
